os: linux
dist: focal

jobs:
  include:
    - name: Image 1
      env: IMAGE_NAME=FRFD_10
      vm:
        create:
          name: FRFD_10
      script:
        - echo "Create FRFD_10"

    - name: Image 2
      env: IMAGE_NAME=image_022
      vm:
        create:
          name: image_022
      script:
        - echo "Create image_022"
