os: osx
osx_image: xcode15.2  # Choose appropriate Xcode version
vm:
  create:
    name: custom_macos_image_example

before_install:
  - brew update
  - brew install libxml2

script:
  - echo "Creating custom macOS (iOS) VM image"
  - xcodebuild -version
