jobs:
  include:
    - stage: use custom image
      os: linux
      dist: focal
      vm:
        use:
          name: tttttt66666
      before_install:
        - sudo apt-get -y install libxml2-dev
      addons:
        apt:
          update: true

    - stage: use custom image
      vm:
        use:
          name: tttttt66666

    - stage: use custom image
      vm:
        use:
          name: tttttt66666
      script:
        - echo "Running build commands"
        - g++ hello.cpp -o hello
        - ./hello
 
